#define _POSIX_C_SOURCE 200809L
#define _DEFAULT_SOURCE
#define _DARWIN_C_SOURCE
#include "db.h"
#include "arena.h"
#include <assert.h>
#include <libpq-fe.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define PG_MAX_ROWS      10000
#define PG_ARG_TEXT_CAP  64
#define PG_SQL_CAP       (DB_MAX_SQL * 2)

static PGconn *g_db;
static pthread_mutex_t g_db_lock = PTHREAD_MUTEX_INITIALIZER;
static _Thread_local int g_last_id;
static _Thread_local int t_depth;
static _Thread_local int t_failed_level;
static int g_busy_ms = 1000;
static int g_query_ms = 5000;

static int db_lock(void)
{
    return (pthread_mutex_lock(&g_db_lock) == 0) ? 0 : -1;
}

static void db_unlock(void)
{
    (void)pthread_mutex_unlock(&g_db_lock);
}

static void db_failure(void)
{
    if ((t_depth != 0) && (t_failed_level == 0)) { t_failed_level = t_depth; }
}

/* The framework speaks '?' placeholders and SQLite's "INTEGER PRIMARY KEY".
   Rewrite both for PostgreSQL, leaving anything inside quotes untouched. */
static int translate(const char *sql, char *out, size_t cap, int *nparams)
{
    assert(sql != NULL);
    assert(out != NULL);

    size_t at = 0u;
    int    n = 0;
    int    in_str = 0;
    int    in_id = 0;

    for (size_t i = 0u; sql[i] != '\0'; i++)
    {
        char c = sql[i];

        if (in_str != 0)
        {
            if (c == '\'') { in_str = 0; }
        }
        else if (in_id != 0)
        {
            if (c == '"') { in_id = 0; }
        }
        else if (c == '\'') { in_str = 1; }
        else if (c == '"') { in_id = 1; }
        else if (c == '?')
        {
            n++;
            int written = snprintf(out + at, cap - at, "$%d", n);
            if ((written < 0) || ((size_t)written >= (cap - at))) { return -1; }
            at += (size_t)written;
            continue;
        }
        else if ((c == 'I') && (strncmp(sql + i, "INTEGER PRIMARY KEY", 19u) == 0))
        {
            const char *rep = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            size_t rl = strlen(rep);
            if ((at + rl) >= cap) { return -1; }
            memcpy(out + at, rep, rl);
            at += rl;
            i += 18u;
            continue;
        }

        if ((at + 1u) >= cap) { return -1; }
        out[at++] = c;
    }

    out[at] = '\0';
    if (nparams != NULL) { *nparams = n; }
    return 0;
}

static int arg_to_text(const SqlArg *a, char *buf, size_t cap, const char **out)
{
    assert(a != NULL);

    int written = 0;
    switch (a->kind)
    {
        case FIELD_INT:    written = snprintf(buf, cap, "%d", a->i); break;
        case FIELD_BOOL:   written = snprintf(buf, cap, "%s", (a->i != 0) ? "true" : "false"); break;
        case FIELD_LONG:   written = snprintf(buf, cap, "%ld", a->l); break;
        case FIELD_DOUBLE: written = snprintf(buf, cap, "%.17g", a->d); break;
        case FIELD_STR:    *out = a->s; return 0;   /* NULL means SQL NULL to PQexecParams */
        default:           return -1;
    }
    if ((written < 0) || ((size_t)written >= cap)) { return -1; }
    *out = buf;
    return 0;
}

/* Caller holds the lock. Returns NULL on failure. */
static PGresult *run(const char *sql, const SqlArg *args, int nargs)
{
    if ((g_db == NULL) || (sql == NULL) || (nargs < 0) || (nargs > DB_MAX_ARGS)) { return NULL; }

    static _Thread_local char sqlbuf[PG_SQL_CAP];
    int wanted = 0;
    if (translate(sql, sqlbuf, sizeof(sqlbuf), &wanted) != 0) { return NULL; }
    if (wanted != nargs) { return NULL; }

    char        store[DB_MAX_ARGS][PG_ARG_TEXT_CAP];
    const char *values[DB_MAX_ARGS];

    for (int i = 0; i < nargs; i++)
    {
        if (arg_to_text(&args[i], store[i], sizeof(store[i]), &values[i]) != 0) { return NULL; }
    }

    PGresult *r = PQexecParams(g_db, sqlbuf, nargs, NULL, (nargs > 0) ? values : NULL, NULL, NULL, 0);
    if (r == NULL) { db_failure(); return NULL; }

    ExecStatusType st = PQresultStatus(r);
    if ((st != PGRES_COMMAND_OK) && (st != PGRES_TUPLES_OK))
    {
        PQclear(r);
        db_failure();
        return NULL;
    }
    return r;
}

str db_name(void)
{
    return "postgres";
}

int db_limits(int busy_ms, int query_ms)
{
    if ((busy_ms < 0) || (query_ms < 0)) { return -1; }
    g_busy_ms = busy_ms;
    g_query_ms = query_ms;
    return 0;
}

int db_open(str url)
{
    if ((url == NULL) || (url[0] == '\0') || (g_db != NULL)) { return -1; }

    g_db = PQconnectdb(url);
    if (g_db == NULL) { return -1; }
    if (PQstatus(g_db) != CONNECTION_OK)
    {
        PQfinish(g_db);
        g_db = NULL;
        return -1;
    }

    char timeout[128];
    int written = snprintf(timeout, sizeof(timeout), "SET statement_timeout = %d", (g_query_ms > 0) ? g_query_ms : 5000);
    if ((written > 0) && ((size_t)written < sizeof(timeout)))
    {
        PGresult *r = PQexec(g_db, timeout);
        if (r != NULL) { PQclear(r); }
    }
    return 0;
}

void db_close(void)
{
    if (g_db != NULL)
    {
        PQfinish(g_db);
        g_db = NULL;
    }
}

int db_ready(void)
{
    return ((g_db != NULL) && (PQstatus(g_db) == CONNECTION_OK)) ? 1 : 0;
}

int db_depth(void)
{
    return t_depth;
}

int db_execute(str sql, const SqlArg *args, int nargs)
{
    if (db_lock() != 0) { return -1; }
    PGresult *r = run(sql, args, nargs);
    if (r == NULL) { db_unlock(); return -1; }

    const char *tuples = PQcmdTuples(r);
    int changed = ((tuples != NULL) && (tuples[0] != '\0')) ? atoi(tuples) : 0;
    PQclear(r);
    db_unlock();
    return changed;
}

int db_last_id(void)
{
    return g_last_id;
}

int db_insert_id(str sql, const SqlArg *args, int nargs)
{
    if (db_lock() != 0) { return -1; }

    PGresult *r = run(sql, args, nargs);
    if (r == NULL) { db_unlock(); return -1; }
    PQclear(r);

    PGresult *id = run("SELECT lastval()", NULL, 0);
    if (id == NULL) { db_unlock(); return -1; }

    int value = -1;
    if ((PQntuples(id) == 1) && (PQnfields(id) == 1) && (PQgetisnull(id, 0, 0) == 0))
    {
        value = atoi(PQgetvalue(id, 0, 0));
    }
    PQclear(id);
    db_unlock();

    if (value < 0) { db_failure(); return -1; }
    g_last_id = value;
    return value;
}

static int read_field(const PGresult *r, int row, const FieldInfo *field, void *obj)
{
    assert(field != NULL);

    int c = PQfnumber(r, field->name);
    if (c < 0) { return -1; }

    char *slot = (char *)obj + field->offset;

    if (PQgetisnull(r, row, c) != 0)
    {
        return ((field->flags & (unsigned)FIELD_NOT_NULL) != 0u) ? -1 : 0;
    }

    const char *text = PQgetvalue(r, row, c);
    if (text == NULL) { return -1; }

    switch (field->kind)
    {
        case FIELD_INT:  { int v = atoi(text); memcpy(slot, &v, sizeof(v)); break; }
        case FIELD_LONG: { long v = strtol(text, NULL, 10); memcpy(slot, &v, sizeof(v)); break; }
        case FIELD_DOUBLE: { double v = strtod(text, NULL); memcpy(slot, &v, sizeof(v)); break; }
        case FIELD_BOOL: { bool v = ((text[0] == 't') || (text[0] == '1')); memcpy(slot, &v, sizeof(v)); break; }
        case FIELD_STR:
        {
            str v = arena_intern(text);
            if (v == NULL) { return -1; }
            memcpy(slot, &v, sizeof(v));
            break;
        }
        default: return -1;
    }
    return 0;
}

static int row_to_struct(const PGresult *r, int row, const TypeInfo *type, void *obj)
{
    if ((type == NULL) || (type->size == 0u) || (type->field_count == 0u) || (type->field_count > 64u) || (type->fields == NULL)) { return -1; }

    memset(obj, 0, type->size);
    for (unsigned f = 0u; (f < type->field_count) && (f < 64u); f++)
    {
        if (read_field(r, row, &type->fields[f], obj) != 0) { return -1; }
    }
    return 0;
}

int db_query_one(const TypeInfo *type, void *out, str sql, const SqlArg *args, int nargs)
{
    if ((type == NULL) || (out == NULL) || (sql == NULL) || (nargs < 0) || (nargs > DB_MAX_ARGS)) { return -1; }
    memset(out, 0, type->size);

    if (db_lock() != 0) { return -1; }
    PGresult *r = run(sql, args, nargs);
    if (r == NULL) { db_unlock(); return -1; }

    int found = 0;
    if (PQntuples(r) > 0) { found = (row_to_struct(r, 0, type, out) == 0) ? 1 : -1; }

    PQclear(r);
    db_unlock();
    if (found < 0) { db_failure(); return -1; }
    return found;
}

int db_query_many(const TypeInfo *type, void *rows, int max, str sql, const SqlArg *args, int nargs)
{
    if ((type == NULL) || (rows == NULL) || (sql == NULL) || (max <= 0) || (max > PG_MAX_ROWS) || (nargs < 0) || (nargs > DB_MAX_ARGS)) { return -1; }

    if (db_lock() != 0) { return -1; }
    PGresult *r = run(sql, args, nargs);
    if (r == NULL) { db_unlock(); return -1; }

    int total = PQntuples(r);
    if (total > max) { total = max; }

    char *base = rows;
    for (int i = 0; i < total; i++)
    {
        if (row_to_struct(r, i, type, base + ((size_t)i * type->size)) != 0)
        {
            PQclear(r);
            db_unlock();
            db_failure();
            return -1;
        }
    }

    PQclear(r);
    db_unlock();
    return total;
}

static int plain(const char *sql)
{
    if (db_lock() != 0) { return -1; }
    PGresult *r = run(sql, NULL, 0);
    if (r == NULL) { db_unlock(); return -1; }
    PQclear(r);
    db_unlock();
    return 0;
}

int db_begin(void)
{
    if (t_depth == 0)
    {
        if (plain("BEGIN") != 0) { return -1; }
        t_depth = 1;
        t_failed_level = 0;
        return 0;
    }

    char sp[64];
    int written = snprintf(sp, sizeof(sp), "SAVEPOINT gg_%d", t_depth + 1);
    if ((written < 0) || ((size_t)written >= sizeof(sp))) { return -1; }
    if (plain(sp) != 0) { return -1; }
    t_depth++;
    return 0;
}

int db_commit(void)
{
    if (t_depth <= 0) { return -1; }
    if ((t_failed_level != 0) && (t_failed_level <= t_depth)) { return -1; }

    if (t_depth == 1)
    {
        if (plain("COMMIT") != 0) { return -1; }
        t_depth = 0;
        t_failed_level = 0;
        return 0;
    }

    char sp[64];
    int written = snprintf(sp, sizeof(sp), "RELEASE SAVEPOINT gg_%d", t_depth);
    if ((written < 0) || ((size_t)written >= sizeof(sp))) { return -1; }
    if (plain(sp) != 0) { return -1; }
    t_depth--;
    return 0;
}

int db_rollback(void)
{
    if (t_depth <= 0) { return -1; }

    if (t_depth == 1)
    {
        int rc = plain("ROLLBACK");
        t_depth = 0;
        t_failed_level = 0;
        return rc;
    }

    char sp[64];
    int written = snprintf(sp, sizeof(sp), "ROLLBACK TO SAVEPOINT gg_%d", t_depth);
    if ((written < 0) || ((size_t)written >= sizeof(sp))) { return -1; }
    int rc = plain(sp);
    t_depth--;
    if (t_failed_level > t_depth) { t_failed_level = 0; }
    return rc;
}

void db_abort_all(void)
{
    while (t_depth > 0) { (void)db_rollback(); }
}

int db_script(const char *sql)
{
    if ((sql == NULL) || (t_depth == 0) || (g_db == NULL)) { return -1; }

    if (db_lock() != 0) { return -1; }
    PGresult *r = PQexec(g_db, sql);
    int ok = 0;
    if (r != NULL)
    {
        ExecStatusType st = PQresultStatus(r);
        ok = ((st == PGRES_COMMAND_OK) || (st == PGRES_TUPLES_OK)) ? 1 : 0;
        PQclear(r);
    }
    db_unlock();
    if (ok == 0) { db_failure(); return -1; }
    return 0;
}

int db_migration_count(void)
{
    if (t_depth == 0) { return -1; }
    if (db_execute("CREATE TABLE IF NOT EXISTS _gargantua_migrations "
                   "(version INTEGER PRIMARY KEY, name TEXT NOT NULL, sql TEXT NOT NULL)", SQL_NOARGS) < 0) { return -1; }

    if (db_lock() != 0) { return -1; }
    PGresult *r = run("SELECT count(*) FROM _gargantua_migrations", NULL, 0);
    int n = -1;
    if (r != NULL)
    {
        if ((PQntuples(r) == 1) && (PQnfields(r) == 1)) { n = atoi(PQgetvalue(r, 0, 0)); }
        PQclear(r);
    }
    db_unlock();
    return n;
}

int db_migration(int version, const char *name, const char *sql, int apply)
{
    if ((t_depth == 0) || (version <= 0) || (name == NULL) || (sql == NULL)) { return -1; }

    if (db_lock() != 0) { return -1; }
    PGresult *r = run("SELECT name, sql FROM _gargantua_migrations WHERE version = ?", SQL_ARGS(SQL_INT(version)));
    if (r == NULL) { db_unlock(); return -1; }

    int exists = (PQntuples(r) > 0) ? 1 : 0;
    int valid = 1;
    if (exists != 0)
    {
        const char *saved_name = PQgetvalue(r, 0, 0);
        const char *saved_sql = PQgetvalue(r, 0, 1);
        valid = ((saved_name != NULL) && (saved_sql != NULL) &&
                 (strcmp(saved_name, name) == 0) && (strcmp(saved_sql, sql) == 0)) ? 1 : 0;
    }
    PQclear(r);
    db_unlock();

    if (valid == 0) { return -1; }
    if (exists != 0) { return 1; }
    if (apply == 0) { return 0; }
    if (db_script(sql) != 0) { return -1; }

    return (db_execute("INSERT INTO _gargantua_migrations(version,name,sql) VALUES (?,?,?)",
                       SQL_ARGS(SQL_INT(version), SQL_TEXT(name), SQL_TEXT(sql))) == 1) ? 1 : -1;
}
